# Generated by Django 4.0.6 on 2022-07-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='Home',
        ),
    ]
