# Generated by Django 4.0.6 on 2022-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_aboutme_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home Page'},
        ),
        migrations.AddField(
            model_name='home',
            name='blog_headingImage',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
