# Generated by Django 4.0.6 on 2022-07-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_home_options_home_blog_headingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(max_length=150)),
                ('date_post', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'My Post',
                'verbose_name_plural': 'My Posts',
            },
        ),
    ]
