# Generated by Django 4.0.6 on 2022-07-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
