# Generated by Django 4.0.6 on 2022-08-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Contact Category',
                'verbose_name_plural': 'Category Contact',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_contact', to='portfolio.contact_category'),
        ),
    ]
