# Generated by Django 4.0.6 on 2022-08-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_choices',
        ),
    ]
