# Generated by Django 4.0.6 on 2022-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_contact_category_delete_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_choices',
            field=models.CharField(choices=[('TAKLIF', 'Taklif'), ('SHIKOYAT', 'Shikoyat')], default='TAKLIF', max_length=10),
        ),
    ]
