# Generated by Django 4.0.6 on 2022-08-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_contact_contact_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-10'),
            preserve_default=False,
        ),
    ]
